version: '2'

services:
  aida-server:
    build: .
    command: /node_modules/ts-node-dev/bin/ts-node-dev --inspect=0.0.0.0:5858 ./src/server.ts
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '5858:5858'
